"""add skill_gap_snapshots

Revision ID: a47bfedbddf1
Revises: ecf98d167202
Create Date: 2026-07-10 16:55:52.158561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a47bfedbddf1'
down_revision: Union[str, Sequence[str], None] = 'ecf98d167202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_gap_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('interview_session_id', sa.UUID(), nullable=True),
    sa.Column('practice_session_id', sa.UUID(), nullable=True),
    sa.Column('jobs_analyzed', sa.Integer(), nullable=False),
    sa.Column('match_ratio', sa.Float(), nullable=False),
    sa.Column('gap_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_session_id'], ['interview_sessions.id'], ),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NB: autogenerate also proposed dropping uq_interview_turns_session_turn_index
    # — a recurring false positive unrelated to this change. Left intact.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('skill_gap_snapshots')
