"""extend roadmaps: snapshot link, summary, progress

Revision ID: bbdf869bf7f8
Revises: a47bfedbddf1
Create Date: 2026-07-10 17:10:18.677436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbdf869bf7f8'
down_revision: Union[str, Sequence[str], None] = 'a47bfedbddf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('snapshot_id', sa.UUID(), nullable=True))
    op.add_column('roadmaps', sa.Column('total_weeks', sa.Integer(), nullable=True))
    op.add_column('roadmaps', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('roadmaps', sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_foreign_key(None, 'roadmaps', 'skill_gap_snapshots', ['snapshot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.drop_column('roadmaps', 'progress')
    op.drop_column('roadmaps', 'summary')
    op.drop_column('roadmaps', 'total_weeks')
    op.drop_column('roadmaps', 'snapshot_id')
    # ### end Alembic commands ###
