"""add practice_sessions and practice_challenges

Revision ID: ecf98d167202
Revises: c3d4e5f6a7b8
Create Date: 2026-07-10 16:20:44.502225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecf98d167202'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('track', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('skills_selected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.Column('verified_strong_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_weak_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('challenge_index', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(length=100), nullable=False),
    sa.Column('challenge_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('starter_code', sa.Text(), nullable=True),
    sa.Column('expected_language', sa.String(length=30), nullable=True),
    sa.Column('evaluation_hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer_code', sa.Text(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('verified_skill_level', sa.String(length=10), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'challenge_index', name='uq_practice_challenge_order')
    )
    op.drop_constraint(op.f('uq_interview_turns_session_turn_index'), 'interview_turns', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_interview_turns_session_turn_index'), 'interview_turns', ['session_id', 'turn_index'], postgresql_nulls_not_distinct=False)
    op.drop_table('practice_challenges')
    op.drop_table('practice_sessions')
    # ### end Alembic commands ###
